apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: i8j8usi35-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:53e60f8eb2521c2bc7a8433a6d63f024bd6a3a3c@sha256:57e51ed47b6f124cd99722f0facc8065b2074dbdbfaf44cf20b2b472a878c3ca
          name: container-image
