apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: i8j8usi35-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: i8j8usi35-go 
  name: i8j8usi35-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: i8j8usi35-go 
